---
output:
   html_document:
      toc: TRUE
      toc_depth: 2
      always_allow_html: TRUE
   word_document:
      toc: TRUE
      toc_depth: 2
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
flextable::set_flextable_defaults(fonts_ignore = TRUE)
# knitr::opts_chunk$set(options(knitr.kable.NA = ''))

plot.settings <- list(what = "std", whatLabels = "no", layout = "tree",
                        intercepts = FALSE, residuals = FALSE, thresholds = FALSE,
                        cut = cut, posCol = c("#BF0000","#000000"), fade = FALSE,
                        # edge.color = , # could create custom function to utilize this argument
                        weighted = TRUE, negDashed = TRUE, esize = 5,
                        manifests = vnames, reorder = FALSE)

```

---
title: "`r report.title`"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
---

# Analysis Summary

**# of folds:** `r k`

**# of variables:** `r nvars`

**# of observations:** `r nobs`

**Maximum # of factors extracted:** `r m`

**Fit across folds by factor model**

```{r model fit, ft.align = "left", results='asis'}
index <- index[index != "df"] 
fit.map <- data.frame(col_keys = names(fit.table),
                      top = c("factors", "df", rep(index, each = 2)),
                      bottom = c("factors", "df", rep(c("mean", "range"), times = length(index))))
border <- officer::fp_border(width = 2)

fit.flex <- flextable::flextable(fit.table)
fit.flex <- flextable::colformat_double(fit.flex, j = -c(1,2), digits = 2)
fit.flex <- flextable::set_header_df(fit.flex, mapping = fit.map)
fit.flex <- flextable::merge_h(fit.flex, part = "header")
fit.flex <- flextable::merge_v(fit.flex, j = c("factors", "df"), part = "header")
fit.flex <- flextable::fix_border_issues(fit.flex)
fit.flex <- flextable::border_inner_h(fit.flex, border = border, part = "header")
fit.flex <- flextable::hline_top(fit.flex, border = border, part = "all")
# fit.flex <- flextable::theme_vanilla(fit.flex)
fit.flex <- flextable::align(fit.flex, align = "center", part = "all")
fit.flex <- flextable::autofit(fit.flex)
knit_print(fit.flex)
```

**Best model in each fold by fit index**

```{r best model, ft.align = "left", results='asis'}
best.flex <- flextab_format(best.model, bold.type = "none", digits = digits)
knit_print(best.flex)
```


# Model Structure

```{r structure, ft.align = "left", results = 'asis', warning = FALSE, message = FALSE, fig.height = 8, fig.width = 12}

for(m in 1:maxfac){
  cat("## Factors:", m)
  cat("\n\n")
  cat("### Across Folds Measures")
  cat("\n\n")
  cat("**Standardized Loading Across Folds**")
  cat("\n\n")
  lambda.flex <- flextab_format(klambdas[[m]], bold.type = "lambda",
                                cut = cut, digits = digits)
  cat(knit_print(lambda.flex))
  cat("\n\n")
  if(m > 1){
  cat("**Mean Factor Correlations**")
  cat("\n\n")
  corr.flex <- flextab_format(kcorrs[[m]], bold.type = "none", digits = digits)
  corr.flex <- flextable::compose(corr.flex, i = 1, j = 1, value = flextable::as_paragraph(""), part = "header")
  cat(knit_print(corr.flex))
  cat("\n\n")
  }
  cat("**Mean Scale Reliabilities**")
  cat("\n\n")
  rel.flex <- flextab_format(as.data.frame(krels[[m]]), bold.type = "none", digits = digits)
  cat(knit_print(rel.flex))
  cat("\n\n")
  cat("### Within Fold Information")
  cat("\n\n")
  for(s in seq_along(kstructures[[m]])){
    cat("**Factor Structure", s, "**")
    cat("\n\n")
    cat("**In Folds:", paste(kstructures[[m]][[s]]$folds, collapse = ", "), "**")
    cat("\n\n")
    cat(gsub("\n", "\n\n", kstructures[[m]][[s]]$structure))
    cat("\n\n")
    l <- length(kstructures[[m]][[s]]$folds)
    plotmat <- matrix(1:l, nrow = ifelse(l < 4, 1, 2), byrow = TRUE)
    graphics::layout(plotmat)
    for(f in kstructures[[m]][[s]]$folds){
    do.call(semPlot::semPaths, args = c(list(object = kfa[[f]][[m]],
                                             color = list(lat = palette.colors(n = m + 1, palette = "Okabe-Ito",
                                                          recycle = TRUE)[-1]),
                                             title = FALSE),
                                        plot.settings))
      title(paste("Fold:", f), adj = 0, line = 0)
    # semPlot::semPaths(object = kfa[[f]][[m]], what = "std", whatLabels = "no", layout = "tree",
    #                     intercepts = FALSE, residuals = FALSE, thresholds = FALSE,
    #                     color = list(lat = palette.colors(n = m + 1, palette = "Okabe-Ito",
    #                                                       recycle = TRUE)[-1]),
    #                     cut = cut, posCol = c("#BF0000","#000000"), fade = FALSE,
    #                     # edge.color = , # could create custom function to utilize this argument
    #                     weighted = TRUE, negDashed = TRUE, esize = 5,
    #                     manifests = vnames, reorder = FALSE)
      cat("\n\n")
  }
 }
}

```


# Appendix - Within Fold Model Fit

```{r appendix, ft.align = "left", results='asis'}
index <- index[index != "df"] 
fit.map <- data.frame(col_keys = names(fit.table),
                      top = c("factors", "df", rep(index, each = 2)),
                      bottom = c("factors", "df", rep(c("mean", "range"), times = length(index))))
border <- officer::fp_border(width = 2)

fit.flex <- flextable::flextable(fit.table)
fit.flex <- flextable::colformat_double(fit.flex, j = -c(1,2), digits = 2)
fit.flex <- flextable::set_header_df(fit.flex, mapping = fit.map)
fit.flex <- flextable::merge_h(fit.flex, part = "header")
fit.flex <- flextable::merge_v(fit.flex, j = c("factors", "df"), part = "header")
fit.flex <- flextable::fix_border_issues(fit.flex)
fit.flex <- flextable::border_inner_h(fit.flex, border = border, part = "header")
fit.flex <- flextable::hline_top(fit.flex, border = border, part = "all")
# fit.flex <- flextable::theme_vanilla(fit.flex)
fit.flex <- flextable::align(fit.flex, align = "center", part = "all")
fit.flex <- flextable::autofit(fit.flex)
knit_print(fit.flex)
```
